name: mobile_calo_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  http: ^1.2.1
  intl: ^0.19.0
  equatable: ^2.0.5
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  web3dart: ^2.7.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^2.0.10+1
  blur: ^4.0.0
  ticket_widget: ^1.0.2
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/google_fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/google_fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Inter-Thin.ttf
          weight: 100

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"